[package]
name = "talaria-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
chitchat = "0.7.0"
tokio = {version = "1.40.0", features = ["sync", "macros", "fs"]}
tonic = "0.12.3"

[build-dependencies]
tonic-build = "0.9.1"
